#!/bin/sh
set -e

# Create privsep user.

getent group deployer-github >/dev/null ||
  groupadd deployer-github -g 64225
getent passwd deployer-github >/dev/null ||
  useradd deployer-github --system -u 64225 -g deployer-github -G deployers -c "Deployer Github Service" -d /nonexistent -s /usr/sbin/nologin

# Create state directory.

install -d -m 0755 -o deployer-github -g deployer-github /var/lib/deployer-github

# Create unix domain socket directory.

install -d -m 0755 -o deployer-github -g deployer-github /var/socket/github-webhooks

# Create daemontools state directories.

install -d -m 0755 -o root -g root /var/lib/supervise/deployer-github
install -d -m 0755 -o root -g root /var/lib/supervise/deployer-github.log

# Create log file directories.

install -d -m 0775 -o root -g deployer-log /var/log/deployer-github

